module.exports = {
  env: {
    browser: true,
    node: true,
  },
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
  },
  extends: [
    './index.js',
    '@vue/typescript/recommended',
    'plugin:vue/vue3-recommended',
    'plugin:import/typescript',
  ],
  plugins: [
    'vue',
  ],
  rules: {
    'arrow-parens': ['error', 'as-needed'],
    'vue/html-closing-bracket-spacing': ['error', {
      startTag: 'never',
      endTag: 'never',
      selfClosingTag: 'never',
    }],
    'vue/multi-word-component-names': ['error', {
      ignores: [
        'index', 'default',
      ],
    }],
    'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
  },
  // global imports from nuxt composables
  globals: {
    prefetchComponents: 'readonly',
    preloadComponents: 'readonly',
    setPageLayout: 'readonly',
    setResponseStatus: 'readonly',
    updateAppConfig: 'readonly',
    useAppConfig: 'readonly',
    useAsyncData: 'readonly',
    useCookie: 'readonly',
    useError: 'readonly',
    useFetch: 'readonly',
    useHead: 'readonly',
    useHydration: 'readonly',
    useLazyAsyncData: 'readonly',
    useLazyFetch: 'readonly',
    useNuxtApp: 'readonly',
    useRequestEvent: 'readonly',
    useRequestHeaders: 'readonly',
    useRoute: 'readonly',
    useRouter: 'readonly',
    useRuntimeConfig: 'readonly',
    useState: 'readonly',
    useSlots: 'readonly',
    $fetch: 'readonly',
    abortNavigation: 'readonly',
    addRouteMiddleware: 'readonly',
    clearError: 'readonly',
    clearNuxtData: 'readonly',
    createError: 'readonly',
    defineNuxtComponent: 'readonly',
    defineNuxtRouteMiddleware: 'readonly',
    definePageMeta: 'readonly',
    navigateTo: 'readonly',
    refreshNuxtData: 'readonly',
    showError: 'readonly',
    defineNuxtPlugin: 'readonly',
    defineEventHandler: 'readonly',
    useBody: 'readonly',
  },
};
